image: docker:19.03.12

variables:
  CONTAINER_IMAGE: "vapprtech/notification:latest"
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

stages:          # List of stages for jobs, and their order of execution
  - build_image
  - deploy_notification

docker-build-image:
  stage: build_image
  script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    #- docker build -t ${CONTAINER_IMAGE} .
    - npm run docker:build
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} vapprtech/notification:latest
    - docker push ${CONTAINER_IMAGE}
  when: always
  only: 
    - main


deploy-notification:
  stage: deploy_notification
  #needs: ["docker-build-image"]
  image: vapprtech/awskubectl:latest
  before_script:
    - aws eks update-kubeconfig --name arrivnow --region us-east-2 
    - kubectl create namespace notification  --dry-run=client -o yaml | kubectl apply -f -   
  script:
    #  - sed -i "s/latest/${CI_COMMIT_SHORT_SHA}/g" manifest/user_management/usermanagementdeployment.yaml
      - cat manifest/notificationdeployment.yaml
      - kubectl apply -f manifest/
      - kubectl get pods -n  notification 
      - kubectl get svc -n notification -o wide
  when: always
  only: 
    - main