apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: vapprtech/notification:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 3000